#!/usr/bin/env python3
"""Swarm Intelligence Monitor - Track and manage multi-agent swarm activity.

Provides visibility into:
- Agent activity across swarms
- Signal convergence detection
- Swarm health and performance
- Decision attribution
"""

import json
import logging
from dataclasses import dataclass, field, asdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional
from enum import Enum
from collections import defaultdict

from src.core.paths import paths

logger = logging.getLogger(__name__)


class SwarmType(Enum):
    TRADING = "trading"
    RESEARCH = "research"
    MODELING = "modeling"
    MACRO = "macro"
    CRISIS = "crisis"


class AgentStatus(Enum):
    IDLE = "idle"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass
class AgentRun:
    """Record of a single agent execution."""
    agent_name: str
    swarm_type: SwarmType
    started_at: datetime
    completed_at: Optional[datetime] = None
    status: AgentStatus = AgentStatus.RUNNING
    task_description: str = ""
    signals_generated: int = 0
    output_files: list = field(default_factory=list)
    error: Optional[str] = None

    def duration_seconds(self) -> float:
        if self.completed_at:
            return (self.completed_at - self.started_at).total_seconds()
        return (datetime.now() - self.started_at).total_seconds()

    def to_dict(self):
        return {
            "agent_name": self.agent_name,
            "swarm_type": self.swarm_type.value,
            "started_at": self.started_at.isoformat(),
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "status": self.status.value,
            "task_description": self.task_description,
            "signals_generated": self.signals_generated,
            "output_files": self.output_files,
            "error": self.error,
            "duration_seconds": self.duration_seconds(),
        }


@dataclass
class SwarmSignal:
    """A signal generated by a swarm agent."""
    agent_name: str
    timestamp: datetime
    symbol: Optional[str]
    signal_type: str
    direction: str  # bullish, bearish, neutral
    confidence: float
    description: str
    metadata: dict = field(default_factory=dict)

    def to_dict(self):
        return {
            "agent_name": self.agent_name,
            "timestamp": self.timestamp.isoformat(),
            "symbol": self.symbol,
            "signal_type": self.signal_type,
            "direction": self.direction,
            "confidence": self.confidence,
            "description": self.description,
            "metadata": self.metadata,
        }


@dataclass
class SignalConvergence:
    """Multiple agents agreeing on a signal."""
    symbol: Optional[str]
    direction: str
    signals: list  # List of SwarmSignal
    convergence_score: float  # Weighted agreement score
    first_signal: datetime

    @property
    def agent_count(self) -> int:
        return len(set(s.agent_name for s in self.signals))

    def to_dict(self):
        return {
            "symbol": self.symbol,
            "direction": self.direction,
            "agent_count": self.agent_count,
            "convergence_score": self.convergence_score,
            "first_signal": self.first_signal.isoformat(),
            "signals": [s.to_dict() for s in self.signals],
        }


@dataclass
class SwarmCycle:
    """A complete swarm execution cycle."""
    cycle_id: str
    swarm_type: SwarmType
    started_at: datetime
    completed_at: Optional[datetime] = None
    agents_run: list = field(default_factory=list)  # List of AgentRun
    signals_generated: list = field(default_factory=list)  # List of SwarmSignal
    convergences_found: list = field(default_factory=list)  # List of SignalConvergence
    decisions_made: list = field(default_factory=list)
    outcome: Optional[str] = None

    def to_dict(self):
        return {
            "cycle_id": self.cycle_id,
            "swarm_type": self.swarm_type.value,
            "started_at": self.started_at.isoformat(),
            "completed_at": self.completed_at.isoformat() if self.completed_at else None,
            "agents_run": [a.to_dict() for a in self.agents_run],
            "signals_generated": [s.to_dict() for s in self.signals_generated],
            "convergences_found": [c.to_dict() for c in self.convergences_found],
            "decisions_made": self.decisions_made,
            "outcome": self.outcome,
        }


class SwarmMonitor:
    """Monitor and manage swarm agent activity."""

    STATE_FILE = paths.live / "swarm_state.json"
    SIGNALS_DIR = paths.live / "signals"
    HISTORY_DIR = paths.base / "swarm_history"

    # Agent to swarm mapping
    AGENT_SWARMS = {
        "critic-agent": SwarmType.TRADING,
        "monitor-agent": SwarmType.TRADING,
        "news-analyst-agent": SwarmType.TRADING,
        "research-agent": SwarmType.RESEARCH,
        "alpha-discovery-agent": SwarmType.RESEARCH,
        "brainstorm-agent": SwarmType.RESEARCH,
        "regime-detector-agent": SwarmType.MODELING,
        "hypothesis-generator-agent": SwarmType.MODELING,
        "text-research-agent": SwarmType.MODELING,
        "macro-research-agent": SwarmType.MACRO,
        "data-acquisition-agent": SwarmType.MACRO,
        "orchestrator-agent": SwarmType.TRADING,  # Special - coordinates others
    }

    # Agent trust weights for convergence scoring
    AGENT_WEIGHTS = {
        "critic-agent": 1.5,
        "monitor-agent": 1.2,
        "research-agent": 1.0,
        "alpha-discovery-agent": 1.0,
        "regime-detector-agent": 1.1,
        "news-analyst-agent": 0.9,
        "brainstorm-agent": 0.8,
        "hypothesis-generator-agent": 0.9,
        "text-research-agent": 0.9,
        "macro-research-agent": 1.0,
        "data-acquisition-agent": 0.7,
    }

    def __init__(self):
        self.current_cycle: Optional[SwarmCycle] = None
        self.active_runs: dict[str, AgentRun] = {}
        self.recent_signals: list[SwarmSignal] = []
        self._load_state()

    def _load_state(self):
        """Load state from file."""
        if self.STATE_FILE.exists():
            try:
                with open(self.STATE_FILE) as f:
                    data = json.load(f)
                # Load recent signals
                for s in data.get("recent_signals", []):
                    self.recent_signals.append(SwarmSignal(
                        agent_name=s["agent_name"],
                        timestamp=datetime.fromisoformat(s["timestamp"]),
                        symbol=s.get("symbol"),
                        signal_type=s["signal_type"],
                        direction=s["direction"],
                        confidence=s["confidence"],
                        description=s["description"],
                        metadata=s.get("metadata", {}),
                    ))
            except Exception as e:
                logger.warning(f"Could not load swarm state: {e}")

    def _save_state(self):
        """Persist state to file."""
        self.STATE_FILE.parent.mkdir(parents=True, exist_ok=True)

        # Prune old signals (keep 7 days)
        cutoff = datetime.now() - timedelta(days=7)
        self.recent_signals = [s for s in self.recent_signals if s.timestamp > cutoff]

        state = {
            "last_updated": datetime.now().isoformat(),
            "active_runs": {k: v.to_dict() for k, v in self.active_runs.items()},
            "recent_signals": [s.to_dict() for s in self.recent_signals[-500:]],  # Keep last 500
            "current_cycle": self.current_cycle.to_dict() if self.current_cycle else None,
        }

        with open(self.STATE_FILE, "w") as f:
            json.dump(state, f, indent=2)

    # === Cycle Management ===

    def start_cycle(self, swarm_type: SwarmType) -> SwarmCycle:
        """Start a new swarm cycle."""
        cycle_id = datetime.now().strftime("%Y%m%d_%H%M%S")
        self.current_cycle = SwarmCycle(
            cycle_id=cycle_id,
            swarm_type=swarm_type,
            started_at=datetime.now(),
        )
        logger.info(f"Started {swarm_type.value} swarm cycle: {cycle_id}")
        self._save_state()
        return self.current_cycle

    def end_cycle(self, outcome: Optional[str] = None):
        """End the current swarm cycle."""
        if self.current_cycle:
            self.current_cycle.completed_at = datetime.now()
            self.current_cycle.outcome = outcome

            # Find convergences
            self.current_cycle.convergences_found = self.find_convergences(
                self.current_cycle.signals_generated
            )

            # Archive cycle
            self._archive_cycle(self.current_cycle)

            logger.info(f"Completed swarm cycle: {self.current_cycle.cycle_id}")
            self.current_cycle = None
            self._save_state()

    def _archive_cycle(self, cycle: SwarmCycle):
        """Archive a completed cycle."""
        self.HISTORY_DIR.mkdir(parents=True, exist_ok=True)
        archive_file = self.HISTORY_DIR / f"cycle_{cycle.cycle_id}.json"
        with open(archive_file, "w") as f:
            json.dump(cycle.to_dict(), f, indent=2)

    # === Agent Run Tracking ===

    def start_agent(self, agent_name: str, task: str = "") -> AgentRun:
        """Record an agent starting execution."""
        swarm_type = self.AGENT_SWARMS.get(agent_name, SwarmType.TRADING)

        run = AgentRun(
            agent_name=agent_name,
            swarm_type=swarm_type,
            started_at=datetime.now(),
            task_description=task,
        )

        self.active_runs[agent_name] = run

        if self.current_cycle:
            self.current_cycle.agents_run.append(run)

        logger.info(f"Agent started: {agent_name}")
        self._save_state()
        return run

    def complete_agent(
        self,
        agent_name: str,
        signals: list[SwarmSignal] = None,
        output_files: list[str] = None,
        error: str = None
    ):
        """Record an agent completing execution."""
        if agent_name in self.active_runs:
            run = self.active_runs[agent_name]
            run.completed_at = datetime.now()
            run.status = AgentStatus.FAILED if error else AgentStatus.COMPLETED
            run.error = error

            if signals:
                run.signals_generated = len(signals)
                self.recent_signals.extend(signals)
                if self.current_cycle:
                    self.current_cycle.signals_generated.extend(signals)

            if output_files:
                run.output_files = output_files

            del self.active_runs[agent_name]
            logger.info(f"Agent completed: {agent_name} ({run.duration_seconds():.1f}s)")
            self._save_state()

    # === Signal Management ===

    def add_signal(self, signal: SwarmSignal):
        """Add a signal from an agent."""
        self.recent_signals.append(signal)
        if self.current_cycle:
            self.current_cycle.signals_generated.append(signal)

        # Also write to signals directory
        self._write_signal_file(signal)
        self._save_state()

    def _write_signal_file(self, signal: SwarmSignal):
        """Write signal to signals directory for stigmergic communication."""
        self.SIGNALS_DIR.mkdir(parents=True, exist_ok=True)

        date_str = signal.timestamp.strftime("%Y%m%d")
        signal_file = self.SIGNALS_DIR / f"{signal.agent_name}_{date_str}.json"

        # Append to existing or create new
        signals = []
        if signal_file.exists():
            with open(signal_file) as f:
                signals = json.load(f)

        signals.append(signal.to_dict())

        with open(signal_file, "w") as f:
            json.dump(signals, f, indent=2)

    def get_recent_signals(
        self,
        max_age_hours: int = 24,
        symbol: str = None,
        agent: str = None
    ) -> list[SwarmSignal]:
        """Get recent signals with optional filtering."""
        cutoff = datetime.now() - timedelta(hours=max_age_hours)
        signals = [s for s in self.recent_signals if s.timestamp > cutoff]

        if symbol:
            signals = [s for s in signals if s.symbol == symbol]
        if agent:
            signals = [s for s in signals if s.agent_name == agent]

        return sorted(signals, key=lambda s: s.timestamp, reverse=True)

    # === Convergence Detection ===

    def find_convergences(
        self,
        signals: list[SwarmSignal] = None,
        min_agents: int = 3,
        max_age_hours: int = 24
    ) -> list[SignalConvergence]:
        """Find signals where multiple agents agree."""
        if signals is None:
            signals = self.get_recent_signals(max_age_hours=max_age_hours)

        # Group by symbol and direction
        groups = defaultdict(list)
        for signal in signals:
            key = (signal.symbol, signal.direction)
            groups[key].append(signal)

        convergences = []
        for (symbol, direction), group_signals in groups.items():
            # Count unique agents
            unique_agents = set(s.agent_name for s in group_signals)

            if len(unique_agents) >= min_agents:
                # Calculate weighted score
                score = sum(
                    self.AGENT_WEIGHTS.get(s.agent_name, 1.0) * s.confidence
                    for s in group_signals
                ) / len(group_signals)

                convergence = SignalConvergence(
                    symbol=symbol,
                    direction=direction,
                    signals=group_signals,
                    convergence_score=score,
                    first_signal=min(s.timestamp for s in group_signals),
                )
                convergences.append(convergence)

        return sorted(convergences, key=lambda c: c.convergence_score, reverse=True)

    # === Reporting ===

    def get_swarm_status(self) -> dict:
        """Get current swarm status for display."""
        return {
            "current_cycle": self.current_cycle.to_dict() if self.current_cycle else None,
            "active_agents": len(self.active_runs),
            "active_runs": {k: v.to_dict() for k, v in self.active_runs.items()},
            "recent_signals_24h": len(self.get_recent_signals(max_age_hours=24)),
            "convergences": [c.to_dict() for c in self.find_convergences()],
            "signals_by_agent": self._count_signals_by_agent(),
            "swarm_health": self._assess_swarm_health(),
        }

    def _count_signals_by_agent(self) -> dict[str, int]:
        """Count recent signals by agent."""
        counts = defaultdict(int)
        for signal in self.get_recent_signals(max_age_hours=24):
            counts[signal.agent_name] += 1
        return dict(counts)

    def _assess_swarm_health(self) -> dict:
        """Assess overall swarm health."""
        signals_24h = self.get_recent_signals(max_age_hours=24)
        active_agents = set(s.agent_name for s in signals_24h)

        return {
            "status": "healthy" if len(active_agents) >= 3 else "degraded",
            "active_agent_count": len(active_agents),
            "signal_rate": len(signals_24h),
            "convergence_count": len(self.find_convergences()),
            "last_activity": max((s.timestamp for s in signals_24h), default=None),
        }

    def generate_report(self) -> str:
        """Generate ASCII report of swarm status."""
        status = self.get_swarm_status()
        health = status["swarm_health"]

        lines = [
            "SWARM INTELLIGENCE STATUS",
            "═" * 60,
            "",
            f"Health: {health['status'].upper()}",
            f"Active Agents: {health['active_agent_count']}",
            f"Signals (24h): {health['signal_rate']}",
            f"Convergences: {health['convergence_count']}",
            "",
        ]

        # Active runs
        if status["active_runs"]:
            lines.append("ACTIVE AGENTS:")
            for name, run in status["active_runs"].items():
                lines.append(f"  • {name}: {run['task_description'][:40]}...")
            lines.append("")

        # Convergences
        if status["convergences"]:
            lines.append("SIGNAL CONVERGENCES:")
            for conv in status["convergences"][:5]:
                symbol = conv["symbol"] or "MARKET"
                direction_emoji = "📈" if conv["direction"] == "bullish" else "📉"
                lines.append(
                    f"  {direction_emoji} {symbol}: {conv['agent_count']} agents "
                    f"({conv['convergence_score']:.0%} confidence)"
                )
            lines.append("")

        # Signals by agent
        if status["signals_by_agent"]:
            lines.append("SIGNALS BY AGENT (24h):")
            for agent, count in sorted(
                status["signals_by_agent"].items(),
                key=lambda x: x[1],
                reverse=True
            )[:7]:
                bar = "█" * min(count, 20)
                lines.append(f"  {agent:25} {bar} {count}")

        lines.append("")
        lines.append("═" * 60)

        return "\n".join(lines)


# Singleton instance
_swarm_monitor: Optional[SwarmMonitor] = None


def get_swarm_monitor() -> SwarmMonitor:
    """Get the singleton swarm monitor instance."""
    global _swarm_monitor
    if _swarm_monitor is None:
        _swarm_monitor = SwarmMonitor()
    return _swarm_monitor


# Convenience functions
def log_agent_signal(
    agent_name: str,
    signal_type: str,
    direction: str,
    confidence: float,
    description: str,
    symbol: str = None,
    metadata: dict = None
):
    """Log a signal from an agent."""
    monitor = get_swarm_monitor()
    signal = SwarmSignal(
        agent_name=agent_name,
        timestamp=datetime.now(),
        symbol=symbol,
        signal_type=signal_type,
        direction=direction,
        confidence=confidence,
        description=description,
        metadata=metadata or {},
    )
    monitor.add_signal(signal)


def get_convergences(min_agents: int = 3) -> list[SignalConvergence]:
    """Get current signal convergences."""
    return get_swarm_monitor().find_convergences(min_agents=min_agents)


if __name__ == "__main__":
    # Demo
    monitor = get_swarm_monitor()
    print(monitor.generate_report())
