"""Cross-Reference Engine.

Reads from multiple data sources and generates alerts by detecting patterns
that no single source would reveal:

1. Insider Divergence: Stock near ATH + insiders selling = RED FLAG
2. Failed Intervention: Gov announces supply action + market rejects = SIGNAL
3. Conviction-Price Divergence: Thesis conviction up but stock price down = INVESTIGATE
4. Concentration + Catalyst: Large position + binary event in 3 days = RISK
5. Regulatory Ceiling: Stock at ATH + regulatory action = HOLD, DON'T ADD

Runs every 30 min. NO network calls — reads only from files on disk.
Must complete in < 30 seconds.
"""

import hashlib
import json
import logging
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional

from src.core.paths import paths

logger = logging.getLogger(__name__)

# Dedup window: same alert_type + symbol within this many hours
DEDUP_HOURS = 4

# Alert severity levels
SEVERITY_RED_FLAG = "red_flag"
SEVERITY_WARNING = "warning"
SEVERITY_INFO = "info"


@dataclass
class CrossReferenceAlert:
    """An alert generated by cross-referencing multiple data sources."""

    alert_id: str
    alert_type: str
    severity: str  # "red_flag", "warning", "info"
    title: str
    description: str
    symbols: list[str]
    theses: list[str]  # thesis names
    data_sources_used: list[str]
    recommended_action: str
    timestamp: str = ""
    evidence: dict = field(default_factory=dict)

    def __post_init__(self):
        if not self.timestamp:
            self.timestamp = datetime.now().isoformat()

    def to_dict(self) -> dict:
        return {
            "alert_id": self.alert_id,
            "alert_type": self.alert_type,
            "severity": self.severity,
            "title": self.title,
            "description": self.description,
            "symbols": self.symbols,
            "theses": self.theses,
            "data_sources_used": self.data_sources_used,
            "recommended_action": self.recommended_action,
            "timestamp": self.timestamp,
            "evidence": self.evidence,
        }


def _make_alert_id(alert_type: str, symbols: list[str]) -> str:
    """Generate deterministic alert_id from type + symbols for dedup."""
    key = f"{alert_type}:{'|'.join(sorted(symbols))}"
    return hashlib.md5(key.encode()).hexdigest()[:12]


class CrossReferenceEngine:
    """Cross-reference multiple data sources to generate automated alerts.

    All data is read from local files — no network calls. Designed to run
    in < 30 seconds as a cron job every 30 minutes.
    """

    def __init__(self):
        self.state: dict = {}
        self.positions: list[dict] = []
        self.market: dict = {}
        self.insider_data: dict = {}
        self.sec_insider_data: dict = {}
        self.treasury_alerts: list[dict] = []
        self.market_reactions: list[dict] = []
        self.news_items: list[dict] = []
        self.signal_digest: dict = {}
        self.theses: list = []  # Thesis objects
        self.existing_alerts: list[dict] = []

    def load_all_sources(self) -> None:
        """Read all data sources from disk. Graceful if files are missing."""
        # 1. State.json — positions, market, alternative signals
        self._load_json(paths.live_state, "_load_state")

        # 2. Insider alerts (from Finviz screens in state.json)
        # Already loaded via state

        # 3. Treasury alerts
        treasury_path = paths.live / "treasury_alerts.json"
        if treasury_path.exists():
            try:
                self.treasury_alerts = json.loads(treasury_path.read_text())
                if isinstance(self.treasury_alerts, dict):
                    self.treasury_alerts = self.treasury_alerts.get("alerts", [])
            except Exception as e:
                logger.debug(f"Treasury alerts not available: {e}")

        # 4. Market reactions (from MarketReactionScorer)
        reactions_path = paths.live / "market_reactions.json"
        if reactions_path.exists():
            try:
                data = json.loads(reactions_path.read_text())
                self.market_reactions = data.get("reactions", [])
            except Exception as e:
                logger.debug(f"Market reactions not available: {e}")

        # 5. News cache
        news_path = paths.live / "news_cache.json"
        if news_path.exists():
            try:
                data = json.loads(news_path.read_text())
                self.news_items = data.get("items", [])
            except Exception as e:
                logger.debug(f"News cache not available: {e}")

        # 6. Signal digest
        digest_path = paths.scheduler / "signal_digest.json"
        if digest_path.exists():
            try:
                self.signal_digest = json.loads(digest_path.read_text())
            except Exception as e:
                logger.debug(f"Signal digest not available: {e}")

        # 7. Theses
        try:
            from src.knowledge.thesis import ThesisTracker
            tracker = ThesisTracker(paths.theses)
            self.theses = tracker.get_active_theses()
        except Exception as e:
            logger.warning(f"Failed to load theses: {e}")

        # 8. SEC insider data (from SECInsiderMonitor)
        sec_file = paths.live / "sec_insider_alerts.json"
        if sec_file.exists():
            try:
                self.sec_insider_data = json.loads(sec_file.read_text())
            except Exception as e:
                logger.debug(f"SEC insider data not available: {e}")

        # 9. Existing alerts (for dedup)
        alerts_path = paths.live / "cross_reference_alerts.json"
        if alerts_path.exists():
            try:
                data = json.loads(alerts_path.read_text())
                self.existing_alerts = data.get("alerts", [])
            except Exception:
                pass

        logger.info(
            f"CrossReferenceEngine loaded: {len(self.positions)} positions, "
            f"{len(self.theses)} theses, {len(self.news_items)} news, "
            f"{len(self.market_reactions)} reactions"
        )

    def _load_json(self, path: Path, handler: str) -> None:
        """Load a JSON file and dispatch to handler."""
        if not path.exists():
            return
        try:
            data = json.loads(path.read_text())
            if handler == "_load_state":
                self.state = data
                self.positions = data.get("positions", [])
                self.market = data.get("market", {})
                # Extract insider data from finviz screens
                alt = data.get("alternative_signals", {})
                finviz = alt.get("screens_finviz", {})
                self.insider_data = {
                    "insider_buying": finviz.get("insider_buying", {}),
                    "institutional_accumulation": finviz.get("institutional_accumulation", {}),
                }
        except Exception as e:
            logger.warning(f"Failed to load {path}: {e}")

    def scan_all(self) -> list[CrossReferenceAlert]:
        """Run all cross-reference checks and return deduplicated alerts."""
        alerts = []

        alerts.extend(self.check_insider_divergence())
        alerts.extend(self.check_failed_interventions())
        alerts.extend(self.check_conviction_price_divergence())
        alerts.extend(self.check_concentration_catalyst())
        alerts.extend(self.check_regulatory_ceiling())

        # Deduplicate against existing alerts
        alerts = self._dedup_alerts(alerts)

        return alerts

    def check_insider_divergence(self) -> list[CrossReferenceAlert]:
        """Detect: stock near 52-week high + 2+ insiders selling.

        Cross-references position performance with insider buying/selling screens
        AND SEC EDGAR Form 4 filings. If SEC data shows 2+ insiders selling a
        symbol that's in our portfolio and near highs, that's a RED FLAG.
        """
        alerts = []
        insider_buying_symbols = set(
            self.insider_data.get("insider_buying", {}).get("symbols", [])
        )
        institutional_symbols = set(
            self.insider_data.get("institutional_accumulation", {}).get("symbols", [])
        )

        # Build SEC insider selling lookup: symbol -> list of sell transactions
        sec_sells_by_symbol: dict[str, list[dict]] = {}
        if self.sec_insider_data:
            for txn in self.sec_insider_data.get("all_transactions", []):
                if txn.get("transaction_type") == "sell":
                    sym = txn.get("symbol", "")
                    sec_sells_by_symbol.setdefault(sym, []).append(txn)

        # Also collect SEC red flags by symbol
        sec_red_flag_symbols: set[str] = set()
        if self.sec_insider_data:
            for rf in self.sec_insider_data.get("red_flags", []):
                sec_red_flag_symbols.add(rf.get("symbol", ""))

        for pos in self.positions:
            symbol = pos.get("symbol", "")
            pnl_pct = pos.get("unrealized_pnl_pct", 0)
            weight_pct = pos.get("weight_pct", 0)

            # Check SEC data for clustered insider selling (2+ sellers)
            sec_sells = sec_sells_by_symbol.get(symbol, [])
            unique_sec_sellers = set(s.get("insider_name", "") for s in sec_sells)
            has_sec_selling = len(unique_sec_sellers) >= 2

            # SEC red flag: 2+ insiders selling near highs — always a red flag
            if has_sec_selling and pnl_pct >= 10:
                total_sold = sum(s.get("total_value", 0) for s in sec_sells)
                seller_names = ", ".join(list(unique_sec_sellers)[:3])
                thesis_names = self._get_thesis_names_for_symbol(symbol)

                severity = SEVERITY_RED_FLAG if symbol in sec_red_flag_symbols else SEVERITY_WARNING
                alerts.append(CrossReferenceAlert(
                    alert_id=_make_alert_id("sec_insider_selling", [symbol]),
                    alert_type="sec_insider_selling",
                    severity=severity,
                    title=f"SEC Insider Selling: {len(unique_sec_sellers)} insiders sold {symbol}",
                    description=(
                        f"{len(unique_sec_sellers)} insiders ({seller_names}) sold {symbol} "
                        f"per SEC Form 4 filings while position is up {pnl_pct:.1f}%. "
                        f"Total insider sales: ${total_sold:,.0f}. "
                        f"Clustered insider selling near highs is a bearish signal."
                    ),
                    symbols=[symbol],
                    theses=thesis_names,
                    data_sources_used=["sec_insider_alerts.json", "state.json"],
                    recommended_action="Do NOT add to position. Tighten stop loss. Review thesis.",
                    evidence={
                        "unrealized_pnl_pct": pnl_pct,
                        "weight_pct": weight_pct,
                        "unique_sellers": len(unique_sec_sellers),
                        "total_value_sold": total_sold,
                        "sellers": list(unique_sec_sellers)[:5],
                        "sec_red_flag": symbol in sec_red_flag_symbols,
                    },
                ))

            # Stock with big gains (proxy for "near highs") but no insider buying
            if pnl_pct >= 20 and weight_pct >= 2:
                if symbol not in insider_buying_symbols and symbol not in institutional_symbols:
                    # Check if there's bearish news on this symbol
                    has_bearish_news = any(
                        symbol in item.get("symbols", [])
                        and any(
                            kw in item.get("headline", "").lower()
                            for kw in ["sell", "downgrade", "warning", "risk", "concern"]
                        )
                        for item in self.news_items
                    )

                    if has_bearish_news or has_sec_selling:
                        severity = SEVERITY_RED_FLAG
                        sec_note = (
                            f" SEC Form 4 shows {len(unique_sec_sellers)} insiders selling."
                            if has_sec_selling else ""
                        )
                        desc = (
                            f"{symbol} is up {pnl_pct:.1f}% (near highs) with bearish news "
                            f"and NO insider/institutional buying detected.{sec_note} "
                            f"Insiders may know something the market doesn't yet."
                        )
                    else:
                        severity = SEVERITY_INFO
                        desc = (
                            f"{symbol} is up {pnl_pct:.1f}% but not appearing in insider "
                            f"buying or institutional accumulation screens. "
                            f"No immediate red flag, but worth monitoring."
                        )

                    thesis_names = self._get_thesis_names_for_symbol(symbol)
                    alerts.append(CrossReferenceAlert(
                        alert_id=_make_alert_id("insider_divergence", [symbol]),
                        alert_type="insider_divergence",
                        severity=severity,
                        title=f"Insider Divergence: {symbol} near highs, no insider buying",
                        description=desc,
                        symbols=[symbol],
                        theses=thesis_names,
                        data_sources_used=["state.json", "screens_finviz", "sec_insider_alerts.json"],
                        recommended_action="Monitor for insider selling filings. Do not add to position.",
                        evidence={
                            "unrealized_pnl_pct": pnl_pct,
                            "weight_pct": weight_pct,
                            "in_insider_buying": False,
                            "has_bearish_news": has_bearish_news,
                            "sec_insider_selling": has_sec_selling,
                        },
                    ))

        return alerts

    def check_failed_interventions(self) -> list[CrossReferenceAlert]:
        """Detect: government/policy action + market rejected the expected outcome.

        Uses market_reactions.json from MarketReactionScorer. Rejected reactions
        where the news was about policy/government action are especially informative.
        """
        alerts = []
        intervention_keywords = [
            "release", "reserve", "stimulus", "fed", "treasury",
            "tariff", "sanction", "regulation", "ban", "policy",
            "government", "administration", "announce", "intervention",
        ]

        for reaction in self.market_reactions:
            if reaction.get("reaction") != "rejected":
                continue

            headline = reaction.get("news_headline", "").lower()
            is_intervention = any(kw in headline for kw in intervention_keywords)

            if not is_intervention:
                continue

            symbols = reaction.get("symbols_checked", [])
            strength = reaction.get("rejection_strength", 0)
            direction = reaction.get("news_direction", "")
            price_4h = reaction.get("price_change_4h", {})

            # Determine signal direction (opposite of failed intervention)
            signal_dir = "bullish" if direction == "bearish" else "bearish"

            severity = SEVERITY_RED_FLAG if strength >= 0.5 else SEVERITY_WARNING
            thesis_names = []
            for sym in symbols:
                thesis_names.extend(self._get_thesis_names_for_symbol(sym))
            thesis_names = list(set(thesis_names))

            alerts.append(CrossReferenceAlert(
                alert_id=_make_alert_id("failed_intervention", symbols),
                alert_type="failed_intervention",
                severity=severity,
                title=f"Failed Intervention: {reaction.get('news_headline', '')[:60]}",
                description=(
                    f"Government/policy action expected {direction} move, but market "
                    f"moved opposite ({signal_dir}). Rejection strength: {strength:.0%}. "
                    f"This is a strong {signal_dir} signal — the market is disagreeing "
                    f"with the intervention."
                ),
                symbols=symbols,
                theses=thesis_names,
                data_sources_used=["market_reactions.json", "news_cache.json"],
                recommended_action=(
                    f"This is a {signal_dir} signal. "
                    + ("Consider adding to positions aligned with market direction."
                       if signal_dir == "bullish"
                       else "Watch for thesis invalidation if this persists.")
                ),
                evidence={
                    "headline": reaction.get("news_headline", ""),
                    "expected_direction": direction,
                    "actual_direction": signal_dir,
                    "rejection_strength": strength,
                    "price_changes_4h": price_4h,
                },
            ))

        return alerts

    def check_conviction_price_divergence(self) -> list[CrossReferenceAlert]:
        """Detect: thesis conviction trending up but stock price trending down (or vice versa).

        Reads conviction_history from thesis objects and compares with position P&L.
        A divergence suggests either the thesis is wrong or the price will catch up.
        """
        alerts = []
        if not self.theses:
            return alerts

        # Build position lookup
        pos_by_symbol = {p["symbol"]: p for p in self.positions}

        for thesis in self.theses:
            conviction_history = thesis.conviction_history
            if len(conviction_history) < 2:
                continue

            # Get conviction trend (last 2-3 updates)
            recent_updates = conviction_history[-3:]
            conviction_delta = recent_updates[-1].new_value - recent_updates[0].old_value

            # Get average P&L for thesis positions
            thesis_pnls = []
            for sym in thesis.positions:
                pos = pos_by_symbol.get(sym)
                if pos:
                    thesis_pnls.append(pos.get("unrealized_pnl_pct", 0))

            if not thesis_pnls:
                continue

            avg_pnl = sum(thesis_pnls) / len(thesis_pnls)

            # Divergence: conviction up but price down
            if conviction_delta >= 5 and avg_pnl <= -5:
                symbols = [s for s in thesis.positions if s in pos_by_symbol]
                alerts.append(CrossReferenceAlert(
                    alert_id=_make_alert_id("conviction_price_divergence", symbols),
                    alert_type="conviction_price_divergence",
                    severity=SEVERITY_WARNING,
                    title=f"Conviction/Price Divergence: {thesis.name}",
                    description=(
                        f"Thesis '{thesis.name}' conviction rose {conviction_delta:+.0f}% "
                        f"(now {thesis.conviction:.0f}%), but positions average "
                        f"{avg_pnl:+.1f}% P&L. Either the thesis is wrong despite growing "
                        f"conviction, or the price will eventually catch up."
                    ),
                    symbols=symbols,
                    theses=[thesis.name],
                    data_sources_used=["theses", "state.json"],
                    recommended_action=(
                        "Review thesis signposts. If fundamentals intact, this may be "
                        "a buying opportunity. If price action is leading, reconsider conviction."
                    ),
                    evidence={
                        "conviction_delta": conviction_delta,
                        "current_conviction": thesis.conviction,
                        "avg_position_pnl": round(avg_pnl, 2),
                        "recent_conviction_updates": [
                            {
                                "timestamp": u.timestamp.isoformat(),
                                "old": u.old_value,
                                "new": u.new_value,
                                "reason": u.reason,
                            }
                            for u in recent_updates
                        ],
                    },
                ))

            # Divergence: conviction down but price up
            elif conviction_delta <= -5 and avg_pnl >= 10:
                symbols = [s for s in thesis.positions if s in pos_by_symbol]
                alerts.append(CrossReferenceAlert(
                    alert_id=_make_alert_id("conviction_price_divergence", symbols),
                    alert_type="conviction_price_divergence",
                    severity=SEVERITY_WARNING,
                    title=f"Conviction Falling, Price Rising: {thesis.name}",
                    description=(
                        f"Thesis '{thesis.name}' conviction dropped {conviction_delta:+.0f}% "
                        f"(now {thesis.conviction:.0f}%), but positions average "
                        f"{avg_pnl:+.1f}% P&L. Price may be ahead of fundamentals. "
                        f"Consider whether gains are momentum-driven."
                    ),
                    symbols=symbols,
                    theses=[thesis.name],
                    data_sources_used=["theses", "state.json"],
                    recommended_action=(
                        "Tighten stops. If conviction is declining for valid reasons, "
                        "price gains may not sustain."
                    ),
                    evidence={
                        "conviction_delta": conviction_delta,
                        "current_conviction": thesis.conviction,
                        "avg_position_pnl": round(avg_pnl, 2),
                    },
                ))

        return alerts

    def check_concentration_catalyst(self) -> list[CrossReferenceAlert]:
        """Detect: large position (>8% portfolio) + binary event within 3 days.

        Cross-references portfolio weights with upcoming events from news/calendar.
        """
        alerts = []
        if not self.positions:
            return alerts

        # Collect symbols with upcoming catalysts from news
        catalyst_symbols: dict[str, list[str]] = {}
        catalyst_keywords = [
            "earnings", "fda", "vote", "ruling", "decision", "deadline",
            "expir", "report", "announce", "launch", "trial", "meeting",
            "rate decision", "pdufa", "approval", "ipo",
        ]

        for item in self.news_items:
            headline = item.get("headline", "").lower()
            symbols = item.get("symbols", [])
            if not symbols:
                continue

            is_catalyst = any(kw in headline for kw in catalyst_keywords)
            if is_catalyst:
                for sym in symbols:
                    catalyst_symbols.setdefault(sym, []).append(
                        item.get("headline", "")[:80]
                    )

        # Also check thesis signposts with upcoming target dates
        now = datetime.now()
        for thesis in self.theses:
            for signpost in thesis.get_pending_signposts():
                if signpost.target_date:
                    try:
                        target = datetime.strptime(signpost.target_date, "%Y-%m-%d")
                        days_until = (target - now).days
                        if 0 <= days_until <= 3:
                            for sym in thesis.positions:
                                catalyst_symbols.setdefault(sym, []).append(
                                    f"Signpost: {signpost.description}"
                                )
                    except ValueError:
                        pass

        # Check concentrated positions with catalysts
        for pos in self.positions:
            symbol = pos.get("symbol", "")
            weight = pos.get("weight_pct", 0)
            if weight < 8:
                continue

            catalysts = catalyst_symbols.get(symbol, [])
            if not catalysts:
                continue

            thesis_names = self._get_thesis_names_for_symbol(symbol)
            alerts.append(CrossReferenceAlert(
                alert_id=_make_alert_id("concentration_catalyst", [symbol]),
                alert_type="concentration_catalyst",
                severity=SEVERITY_RED_FLAG,
                title=f"Concentrated Position + Catalyst: {symbol} ({weight:.1f}%)",
                description=(
                    f"{symbol} is {weight:.1f}% of portfolio with upcoming catalyst(s): "
                    f"{'; '.join(catalysts[:3])}. Binary event risk on a concentrated position."
                ),
                symbols=[symbol],
                theses=thesis_names,
                data_sources_used=["state.json", "news_cache.json", "theses"],
                recommended_action=(
                    f"Consider trimming {symbol} to <8% before catalyst, or ensure "
                    f"thesis conviction supports holding through the event."
                ),
                evidence={
                    "weight_pct": weight,
                    "catalysts": catalysts[:5],
                    "unrealized_pnl_pct": pos.get("unrealized_pnl_pct", 0),
                },
            ))

        return alerts

    def check_regulatory_ceiling(self) -> list[CrossReferenceAlert]:
        """Detect: stock at/near ATH + regulatory news = potential ceiling.

        Warns against adding to positions where regulatory headwinds may cap upside.
        """
        alerts = []
        regulatory_keywords = [
            "regulat", "antitrust", "doj", "ftc", "sec", "investigate",
            "probe", "lawsuit", "fine", "penalty", "compliance",
            "subpoena", "enforcement", "violation",
        ]

        # Find symbols with regulatory news
        regulatory_symbols: dict[str, list[str]] = {}
        for item in self.news_items:
            headline = item.get("headline", "").lower()
            symbols = item.get("symbols", [])
            if not symbols:
                continue

            has_regulatory = any(kw in headline for kw in regulatory_keywords)
            if has_regulatory:
                for sym in symbols:
                    regulatory_symbols.setdefault(sym, []).append(
                        item.get("headline", "")[:80]
                    )

        # Check portfolio positions near highs + regulatory news
        for pos in self.positions:
            symbol = pos.get("symbol", "")
            pnl_pct = pos.get("unrealized_pnl_pct", 0)

            if symbol not in regulatory_symbols:
                continue

            # Stock near highs (big gains = proxy for near ATH)
            if pnl_pct >= 15:
                headlines = regulatory_symbols[symbol]
                thesis_names = self._get_thesis_names_for_symbol(symbol)

                alerts.append(CrossReferenceAlert(
                    alert_id=_make_alert_id("regulatory_ceiling", [symbol]),
                    alert_type="regulatory_ceiling",
                    severity=SEVERITY_WARNING,
                    title=f"Regulatory Ceiling Risk: {symbol} at +{pnl_pct:.0f}%",
                    description=(
                        f"{symbol} is up {pnl_pct:.1f}% (near highs) with regulatory "
                        f"headwinds: {headlines[0]}. Regulatory action may cap further "
                        f"upside. Hold existing position but do not add."
                    ),
                    symbols=[symbol],
                    theses=thesis_names,
                    data_sources_used=["state.json", "news_cache.json"],
                    recommended_action="HOLD, DON'T ADD. Wait for regulatory clarity.",
                    evidence={
                        "unrealized_pnl_pct": pnl_pct,
                        "regulatory_headlines": headlines[:3],
                    },
                ))

        return alerts

    def _get_thesis_names_for_symbol(self, symbol: str) -> list[str]:
        """Get thesis names for a symbol."""
        names = []
        for thesis in self.theses:
            if symbol in thesis.positions:
                names.append(thesis.name)
        return names

    def _dedup_alerts(self, alerts: list[CrossReferenceAlert]) -> list[CrossReferenceAlert]:
        """Remove alerts that duplicate recent ones (same type + symbol within DEDUP_HOURS)."""
        cutoff = datetime.now() - timedelta(hours=DEDUP_HOURS)
        recent_keys = set()

        for existing in self.existing_alerts:
            try:
                ts = datetime.fromisoformat(existing.get("timestamp", ""))
                if ts >= cutoff:
                    key = f"{existing.get('alert_type')}:{'|'.join(sorted(existing.get('symbols', [])))}"
                    recent_keys.add(key)
            except (ValueError, TypeError):
                pass

        deduped = []
        for alert in alerts:
            key = f"{alert.alert_type}:{'|'.join(sorted(alert.symbols))}"
            if key not in recent_keys:
                deduped.append(alert)
                recent_keys.add(key)

        if len(alerts) != len(deduped):
            logger.info(f"Deduped {len(alerts) - len(deduped)} alerts (repeated within {DEDUP_HOURS}h)")

        return deduped

    def save_alerts(self, alerts: list[CrossReferenceAlert]) -> Path:
        """Save alerts to cross_reference_alerts.json.

        Appends new alerts to existing ones, keeping last 24 hours.
        """
        output_path = paths.live / "cross_reference_alerts.json"
        cutoff = datetime.now() - timedelta(hours=24)

        # Keep recent existing alerts
        recent_existing = []
        for existing in self.existing_alerts:
            try:
                ts = datetime.fromisoformat(existing.get("timestamp", ""))
                if ts >= cutoff:
                    recent_existing.append(existing)
            except (ValueError, TypeError):
                pass

        all_alerts = recent_existing + [a.to_dict() for a in alerts]

        data = {
            "last_scanned": datetime.now().isoformat(),
            "total_alerts": len(all_alerts),
            "red_flags": sum(1 for a in all_alerts if a.get("severity") == SEVERITY_RED_FLAG),
            "warnings": sum(1 for a in all_alerts if a.get("severity") == SEVERITY_WARNING),
            "new_alerts_this_scan": len(alerts),
            "alerts": all_alerts,
        }

        try:
            output_path.write_text(json.dumps(data, indent=2))
            logger.info(f"Saved {len(alerts)} new alerts ({len(all_alerts)} total) to {output_path}")
        except Exception as e:
            logger.error(f"Failed to save cross-reference alerts: {e}")

        return output_path

    def push_to_situation_board(self, alerts: list[CrossReferenceAlert]) -> None:
        """Push red_flag and warning alerts to the situation board.

        Only pushes alerts with severity >= warning.
        """
        actionable = [a for a in alerts if a.severity in (SEVERITY_RED_FLAG, SEVERITY_WARNING)]
        if not actionable:
            return

        try:
            from src.swarm.situation_board import SituationBoard

            board = SituationBoard.load()
            for alert in actionable:
                board.add_observation(
                    source="cross_reference",
                    obs_type="alert" if alert.severity == SEVERITY_RED_FLAG else "assessment",
                    text=f"[{alert.severity.upper()}] {alert.title}: {alert.recommended_action}",
                    symbols=alert.symbols,
                    thesis=alert.theses[0] if alert.theses else None,
                    action="monitor" if alert.severity == SEVERITY_WARNING else "recommend_trade",
                )
            board.save()
            logger.info(f"Pushed {len(actionable)} alerts to situation board")
        except Exception as e:
            logger.warning(f"Failed to push alerts to situation board: {e}")

    def run(self) -> list[CrossReferenceAlert]:
        """Full pipeline: load sources, scan, save, push."""
        self.load_all_sources()
        alerts = self.scan_all()
        self.save_alerts(alerts)
        self.push_to_situation_board(alerts)
        return alerts
