"""Signal definitions for trading strategies."""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any
from uuid import uuid4

from .types import Direction, SignalStrength, SignalType, Symbol, UnitFloat


@dataclass
class Signal:
    """
    A trading signal generated by a strategy or agent.

    Attributes:
        timestamp: When the signal was generated
        symbol: The asset symbol
        direction: Long, short, or flat
        strength: Signal strength from -1 (strong short) to 1 (strong long)
        confidence: Confidence level from 0 to 1
        signal_type: Type of signal (entry, exit, etc.)
        strategy_name: Name of the strategy that generated the signal
        metadata: Additional signal metadata
    """

    timestamp: datetime
    symbol: Symbol
    direction: Direction
    strength: SignalStrength
    confidence: UnitFloat = 0.5
    signal_type: SignalType = SignalType.ENTRY_LONG
    strategy_name: str = ""
    metadata: dict[str, Any] = field(default_factory=dict)
    signal_id: str = field(default_factory=lambda: str(uuid4()))

    def __post_init__(self) -> None:
        """Validate signal values."""
        if not -1 <= self.strength <= 1:
            raise ValueError(f"strength must be between -1 and 1, got {self.strength}")
        if not 0 <= self.confidence <= 1:
            raise ValueError(f"confidence must be between 0 and 1, got {self.confidence}")

        # Infer signal type from direction if not set
        if self.signal_type == SignalType.ENTRY_LONG and self.direction == Direction.SHORT:
            self.signal_type = SignalType.ENTRY_SHORT

    @property
    def is_buy(self) -> bool:
        """Check if this is a buy signal."""
        return self.direction == Direction.LONG and self.strength > 0

    @property
    def is_sell(self) -> bool:
        """Check if this is a sell signal."""
        return self.direction == Direction.SHORT and self.strength < 0

    @property
    def is_exit(self) -> bool:
        """Check if this is an exit signal."""
        return self.signal_type in (SignalType.EXIT_LONG, SignalType.EXIT_SHORT)

    @property
    def weighted_strength(self) -> float:
        """Return strength weighted by confidence."""
        return self.strength * self.confidence

    def to_dict(self) -> dict[str, Any]:
        """Convert signal to dictionary."""
        return {
            "signal_id": self.signal_id,
            "timestamp": self.timestamp.isoformat(),
            "symbol": self.symbol,
            "direction": self.direction.value,
            "strength": self.strength,
            "confidence": self.confidence,
            "signal_type": self.signal_type.value,
            "strategy_name": self.strategy_name,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Signal":
        """Create signal from dictionary."""
        return cls(
            signal_id=data.get("signal_id", str(uuid4())),
            timestamp=datetime.fromisoformat(data["timestamp"]),
            symbol=data["symbol"],
            direction=Direction(data["direction"]),
            strength=data["strength"],
            confidence=data.get("confidence", 0.5),
            signal_type=SignalType(data.get("signal_type", "entry_long")),
            strategy_name=data.get("strategy_name", ""),
            metadata=data.get("metadata", {}),
        )


@dataclass
class SignalBundle:
    """A collection of signals at a single timestamp."""

    timestamp: datetime
    signals: list[Signal] = field(default_factory=list)

    def __len__(self) -> int:
        return len(self.signals)

    def __iter__(self):
        return iter(self.signals)

    def for_symbol(self, symbol: str) -> list[Signal]:
        """Get all signals for a specific symbol."""
        return [s for s in self.signals if s.symbol == symbol]

    def by_direction(self, direction: Direction) -> list[Signal]:
        """Get all signals for a specific direction."""
        return [s for s in self.signals if s.direction == direction]

    @property
    def symbols(self) -> set[str]:
        """Get unique symbols in bundle."""
        return {s.symbol for s in self.signals}

    def aggregate(self, method: str = "mean") -> dict[str, float]:
        """
        Aggregate signals by symbol.

        Args:
            method: Aggregation method - 'mean', 'weighted_mean', 'max'

        Returns:
            Dictionary mapping symbols to aggregated signal strength
        """
        result: dict[str, float] = {}

        for symbol in self.symbols:
            symbol_signals = self.for_symbol(symbol)

            if method == "mean":
                result[symbol] = sum(s.strength for s in symbol_signals) / len(symbol_signals)
            elif method == "weighted_mean":
                total_confidence = sum(s.confidence for s in symbol_signals)
                if total_confidence > 0:
                    result[symbol] = (
                        sum(s.weighted_strength for s in symbol_signals) / total_confidence
                    )
                else:
                    result[symbol] = 0.0
            elif method == "max":
                result[symbol] = max((s.strength for s in symbol_signals), key=abs)
            else:
                raise ValueError(f"Unknown aggregation method: {method}")

        return result
