#!/bin/bash
# Athena Multi-Instance Launcher
#
# Manages parallel Athena instances, each with isolated:
#   - Results directory (~/quant_results_<name>)
#   - Alpaca credentials (config/credentials_<name>.yaml)
#   - tmux session (athena-<name>)
#
# Usage:
#   ./scripts/instance_launcher.sh create <name> <alpaca_api_key> <alpaca_secret_key>
#   ./scripts/instance_launcher.sh start <name>
#   ./scripts/instance_launcher.sh stop <name>
#   ./scripts/instance_launcher.sh status [name|all]
#   ./scripts/instance_launcher.sh list
#   ./scripts/instance_launcher.sh destroy <name>

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# --- Helpers ---

log_info() { echo "[INFO] $*"; }
log_error() { echo "[ERROR] $*" >&2; }

validate_name() {
    local NAME="$1"
    if [[ "$NAME" == "default" ]]; then
        log_error "Cannot use 'default' as instance name (reserved for ~/quant_results)"
        exit 1
    fi
    if [[ ! "$NAME" =~ ^[a-z][a-z0-9_-]*$ ]]; then
        log_error "Instance name must be lowercase alphanumeric (with hyphens/underscores), starting with a letter"
        exit 1
    fi
}

results_dir_for() {
    echo "$HOME/quant_results_${1}"
}

# --- Commands ---

cmd_create() {
    local NAME="$1"
    local API_KEY="$2"
    local SECRET_KEY="$3"

    validate_name "$NAME"

    local RESULTS_DIR
    RESULTS_DIR="$(results_dir_for "$NAME")"

    if [ -d "$RESULTS_DIR" ]; then
        log_error "Instance '$NAME' already exists at $RESULTS_DIR"
        log_error "Use '$0 destroy $NAME' first, or start it with '$0 start $NAME'"
        exit 1
    fi

    log_info "Creating Athena instance: $NAME"
    log_info "  Results directory: $RESULTS_DIR"

    # Create directory structure (mirrors default instance)
    mkdir -p "$RESULTS_DIR"/{live/research,live/news,theses,decisions,learnings}
    mkdir -p "$RESULTS_DIR"/{knowledge/companies,knowledge/sectors}
    mkdir -p "$RESULTS_DIR"/{intelligence,briefings}
    mkdir -p "$RESULTS_DIR"/{scheduler/completions,scheduler/locks}
    mkdir -p "$RESULTS_DIR"/{logs,signal_provenance,signal_quality,social}
    mkdir -p "$RESULTS_DIR"/{scraped_data/finviz,alpha_discovery}
    mkdir -p "$RESULTS_DIR"/{validation_reports,comprehensive_research}
    mkdir -p "$RESULTS_DIR"/{full_research,research_tracker}
    mkdir -p "$RESULTS_DIR"/{war,parallel,risk_reports,accounts}

    # Create credentials file
    local CREDS_FILE="$PROJECT_DIR/config/credentials_${NAME}.yaml"
    cat > "$CREDS_FILE" << YAML
# Athena instance: $NAME
# Auto-generated by instance_launcher.sh
alpaca:
  api_key: ${API_KEY}
  secret_key: ${SECRET_KEY}
  paper: true
YAML

    # Initialize empty state.json
    python3 -c "
import json
from datetime import datetime
state = {
    'timestamp': datetime.now().isoformat(),
    'portfolio': {
        'equity': 100000,
        'cash': 100000,
        'total_positions': 0,
        'market_exposure_pct': 0.0
    },
    'positions': [],
    'market_regime': {},
    'signals': [],
    'alternative_signals': {},
    'news_events': []
}
with open('$RESULTS_DIR/live/state.json', 'w') as f:
    json.dump(state, f, indent=2)
"

    # Initialize empty athena.db
    QUANT_RESULTS_DIR="$RESULTS_DIR" ATHENA_INSTANCE="$NAME" python3 -c "
import sys
sys.path.insert(0, '$PROJECT_DIR')
try:
    from src.db.database import get_engine, Base
    engine = get_engine()
    Base.metadata.create_all(engine)
    print('  Database initialized')
except Exception as e:
    print(f'  DB init skipped: {e}')
" 2>/dev/null || true

    log_info "Instance '$NAME' created successfully."
    echo ""
    echo "  Credentials: config/credentials_${NAME}.yaml"
    echo "  Results dir: $RESULTS_DIR"
    echo "  Start with:  $0 start $NAME"
}

cmd_start() {
    local NAME="$1"

    validate_name "$NAME"

    local RESULTS_DIR
    RESULTS_DIR="$(results_dir_for "$NAME")"
    local TMUX_SESSION="athena-${NAME}"

    if [ ! -d "$RESULTS_DIR" ]; then
        log_error "Instance '$NAME' not found at $RESULTS_DIR"
        log_error "Create it first: $0 create $NAME <api_key> <secret_key>"
        exit 1
    fi

    if tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
        log_info "Instance '$NAME' already running (tmux: $TMUX_SESSION)"
        echo "  Attach with: tmux attach -t $TMUX_SESSION"
        return 0
    fi

    log_info "Starting Athena instance: $NAME"
    log_info "  QUANT_RESULTS_DIR=$RESULTS_DIR"
    log_info "  ATHENA_INSTANCE=$NAME"
    log_info "  tmux session: $TMUX_SESSION"

    # Start tmux session via athena_scheduler.sh
    QUANT_RESULTS_DIR="$RESULTS_DIR" ATHENA_INSTANCE="$NAME" \
        "$SCRIPT_DIR/athena_scheduler.sh" setup

    log_info "Instance '$NAME' started."
    echo "  Attach with: tmux attach -t $TMUX_SESSION"
}

cmd_stop() {
    local NAME="$1"

    validate_name "$NAME"

    local TMUX_SESSION="athena-${NAME}"

    if tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
        # Try graceful sentinel stop first
        local RESULTS_DIR
        RESULTS_DIR="$(results_dir_for "$NAME")"
        if [ -f "$RESULTS_DIR/scheduler/sentinel.pid" ]; then
            local PID
            PID=$(cat "$RESULTS_DIR/scheduler/sentinel.pid" 2>/dev/null || echo "")
            if [ -n "$PID" ] && kill -0 "$PID" 2>/dev/null; then
                log_info "Stopping sentinel (PID $PID)..."
                kill "$PID" 2>/dev/null || true
                sleep 1
            fi
        fi

        log_info "Stopping tmux session: $TMUX_SESSION"
        tmux kill-session -t "$TMUX_SESSION" 2>/dev/null
        log_info "Instance '$NAME' stopped."
    else
        log_info "Instance '$NAME' is not running."
    fi
}

cmd_status() {
    local NAME="${1:-all}"

    if [ "$NAME" = "all" ]; then
        echo "=== Athena Instances ==="

        # Default instance
        echo ""
        echo "--- default ---"
        if tmux has-session -t athena-auto 2>/dev/null; then
            echo "  Status:  RUNNING (tmux: athena-auto)"
        else
            echo "  Status:  STOPPED"
        fi
        echo "  Dir:     $HOME/quant_results"
        if [ -f "$HOME/quant_results/live/state.json" ]; then
            python3 -c "
import json
with open('$HOME/quant_results/live/state.json') as f:
    s = json.load(f)
p = s.get('portfolio', {})
print(f'  Equity:  \${p.get(\"equity\", 0):,.0f} | Cash: \${p.get(\"cash\", 0):,.0f} | Positions: {p.get(\"total_positions\", 0)}')
" 2>/dev/null || true
        fi

        # Named instances
        for dir in "$HOME"/quant_results_*; do
            if [ -d "$dir" ]; then
                local iname
                iname=$(basename "$dir" | sed 's/quant_results_//')
                echo ""
                echo "--- $iname ---"
                if tmux has-session -t "athena-${iname}" 2>/dev/null; then
                    echo "  Status:  RUNNING (tmux: athena-${iname})"
                else
                    echo "  Status:  STOPPED"
                fi
                echo "  Dir:     $dir"
                if [ -f "$dir/live/state.json" ]; then
                    python3 -c "
import json
with open('$dir/live/state.json') as f:
    s = json.load(f)
p = s.get('portfolio', {})
print(f'  Equity:  \${p.get(\"equity\", 0):,.0f} | Cash: \${p.get(\"cash\", 0):,.0f} | Positions: {p.get(\"total_positions\", 0)}')
" 2>/dev/null || true
                fi
            fi
        done
        echo ""
    else
        # Single instance status
        validate_name "$NAME"
        local TMUX_SESSION="athena-${NAME}"
        local RDIR
        RDIR="$(results_dir_for "$NAME")"

        echo "Instance: $NAME"
        if [ ! -d "$RDIR" ]; then
            echo "  Status:  NOT CREATED"
            return
        fi
        if tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
            echo "  Status:  RUNNING (tmux: $TMUX_SESSION)"
        else
            echo "  Status:  STOPPED"
        fi
        echo "  Dir:     $RDIR"
        echo "  Creds:   config/credentials_${NAME}.yaml"

        if [ -f "$RDIR/live/state.json" ]; then
            python3 -c "
import json, os
from datetime import datetime
with open('$RDIR/live/state.json') as f:
    s = json.load(f)
p = s.get('portfolio', {})
ts = s.get('timestamp', 'unknown')
print(f'  Equity:  \${p.get(\"equity\", 0):,.0f} | Cash: \${p.get(\"cash\", 0):,.0f} | Positions: {p.get(\"total_positions\", 0)}')
print(f'  Updated: {ts}')
" 2>/dev/null || true
        fi

        # Check sentinel
        if [ -f "$RDIR/scheduler/sentinel.pid" ]; then
            local PID
            PID=$(cat "$RDIR/scheduler/sentinel.pid" 2>/dev/null || echo "")
            if [ -n "$PID" ] && kill -0 "$PID" 2>/dev/null; then
                echo "  Sentinel: RUNNING (PID $PID)"
            else
                echo "  Sentinel: STOPPED (stale PID file)"
            fi
        else
            echo "  Sentinel: NOT STARTED"
        fi
    fi
}

cmd_list() {
    echo "Athena instances:"
    echo "  default  ->  $HOME/quant_results"
    for dir in "$HOME"/quant_results_*; do
        if [ -d "$dir" ]; then
            local iname
            iname=$(basename "$dir" | sed 's/quant_results_//')
            local status="stopped"
            if tmux has-session -t "athena-${iname}" 2>/dev/null; then
                status="running"
            fi
            echo "  $iname  ->  $dir  [$status]"
        fi
    done
}

cmd_destroy() {
    local NAME="$1"

    validate_name "$NAME"

    local RESULTS_DIR
    RESULTS_DIR="$(results_dir_for "$NAME")"
    local TMUX_SESSION="athena-${NAME}"
    local CREDS_FILE="$PROJECT_DIR/config/credentials_${NAME}.yaml"

    if [ ! -d "$RESULTS_DIR" ]; then
        log_error "Instance '$NAME' does not exist."
        exit 1
    fi

    # Stop if running
    if tmux has-session -t "$TMUX_SESSION" 2>/dev/null; then
        cmd_stop "$NAME"
    fi

    echo ""
    echo "WARNING: This will permanently delete:"
    echo "  $RESULTS_DIR"
    echo "  $CREDS_FILE (if exists)"
    echo ""
    read -p "Type '$NAME' to confirm destruction: " CONFIRM
    if [ "$CONFIRM" != "$NAME" ]; then
        echo "Cancelled."
        exit 0
    fi

    rm -rf "$RESULTS_DIR"
    rm -f "$CREDS_FILE"
    log_info "Instance '$NAME' destroyed."
}

# --- Main dispatch ---

case "${1:-help}" in
    create)
        cmd_create "${2:?name required}" "${3:?api_key required}" "${4:?secret_key required}"
        ;;
    start)
        cmd_start "${2:?name required}"
        ;;
    stop)
        cmd_stop "${2:?name required}"
        ;;
    status)
        cmd_status "${2:-all}"
        ;;
    list)
        cmd_list
        ;;
    destroy)
        cmd_destroy "${2:?name required}"
        ;;
    help|--help|-h|*)
        echo "Athena Multi-Instance Launcher"
        echo ""
        echo "Usage:"
        echo "  $0 create  <name> <api_key> <secret_key>  Create a new instance"
        echo "  $0 start   <name>                         Start an instance (tmux + scheduler)"
        echo "  $0 stop    <name>                         Stop an instance"
        echo "  $0 status  [name|all]                     Show instance status"
        echo "  $0 list                                   List all instances"
        echo "  $0 destroy <name>                         Permanently delete an instance"
        echo ""
        echo "Each instance gets:"
        echo "  ~/quant_results_<name>/          Isolated state, theses, decisions"
        echo "  config/credentials_<name>.yaml   Separate Alpaca paper account"
        echo "  tmux session: athena-<name>      Separate terminal"
        echo ""
        echo "Environment variables set per instance:"
        echo "  QUANT_RESULTS_DIR   Points to instance results directory"
        echo "  ATHENA_INSTANCE     Instance name (for credential routing)"
        ;;
esac
